#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# Ejecuta 02_oracle_client_diag.sh para varios caminos/targets definidos en CSV.
#
# Uso:
#   ./06_run_targets.sh [targets.csv] [output_dir]
#   ./06_run_targets.sh --report-only output_dir
#
# CSV esperado:
# target_name,dest_host,dest_oratcp_port,db_host,db_port,tns_alias,dblink_name,db_version,iface,capture_seconds,capture_mode
###############################################################################

HOST="$(hostname -s 2>/dev/null || hostname)"
TS="$(date +%Y%m%d_%H%M%S)"
CLIENT_SCRIPT="${CLIENT_SCRIPT:-./02_oracle_client_diag.sh}"
REPORT_ONLY=0

usage() {
  cat <<'USAGE'
Uso:
  ./06_run_targets.sh targets.csv diag_paths_HAB
  ./06_run_targets.sh --report-only diag_paths_HAB

El CSV debe incluir:
target_name,dest_host,dest_oratcp_port,db_host,db_port,tns_alias,dblink_name,db_version,iface,capture_seconds,capture_mode
USAGE
}

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  usage
  exit 0
fi

if [[ "${1:-}" == "--report-only" ]]; then
  REPORT_ONLY=1
  CONFIG="report-only"
  OUT_ROOT="${2:-}"
  if [[ -z "$OUT_ROOT" ]]; then
    echo "ERROR: falta output_dir para --report-only"
    exit 1
  fi
  if [[ ! -d "$OUT_ROOT" ]]; then
    echo "ERROR: no existe el directorio $OUT_ROOT"
    exit 1
  fi
else
  CONFIG="${1:-targets.csv}"
  OUT_ROOT="${2:-diag_paths_${HOST}_${TS}}"

  if [[ ! -f "$CONFIG" ]]; then
    echo "ERROR: no existe $CONFIG"
    echo "Crea el archivo desde targets.csv.example y completa los valores SCL/VLP."
    exit 1
  fi

  if [[ ! -x "$CLIENT_SCRIPT" ]]; then
    echo "ERROR: $CLIENT_SCRIPT no existe o no es ejecutable"
    exit 1
  fi
fi

mkdir -p "$OUT_ROOT"

COMPARISON_CSV="${OUT_ROOT}/comparison.csv"
COMPARISON_MD="${OUT_ROOT}/comparison.md"
RUN_LOG="${OUT_ROOT}/run_targets.log"

trim() {
  local value="$*"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "$value"
}

sanitize_name() {
  local value="$1"
  value="${value//[^A-Za-z0-9_.-]/_}"
  [[ -n "$value" ]] || value="target"
  printf '%s' "$value"
}

csv_escape() {
  local value="${1:-}"
  value="${value//$'\n'/ }"
  value="${value//\"/\"\"}"
  printf '"%s"' "$value"
}

append_csv_row() {
  local values=("$@")
  local first=1
  for value in "${values[@]}"; do
    if [[ "$first" -eq 0 ]]; then
      printf ',' >> "$COMPARISON_CSV"
    fi
    csv_escape "$value" >> "$COMPARISON_CSV"
    first=0
  done
  printf '\n' >> "$COMPARISON_CSV"
}

metric_or_blank() {
  local key="$1"
  local file="$2"
  [[ -f "$file" ]] || return 0
  (
    set +u
    # metrics.env is generated by 02_oracle_client_diag.sh using shell-safe quoting.
    # shellcheck disable=SC1090
    source "$file"
    printf '%s' "${!key:-}"
  )
}

write_headers() {
  printf '%s\n' \
    'target_name,outdir,db_listener,route_dev,route_via,route_src,ping_loss_pct,ping_avg_ms,tnsping_ms,nc_status,oratcp_small_summary,oratcp_medium_summary,dblink_single_row_elapsed_ms,dblink_multi_row_elapsed_ms,dblink_repeated_calls_elapsed_ms,dblink_total_roundtrips_delta,dblink_total_bytes_sent_delta,dblink_total_bytes_received_delta,tcp_retransmissions_db,tcp_retransmissions_oratcp,tcp_retransmissions_failover,pcap_db,pcap_failover' \
    > "$COMPARISON_CSV"

  {
    echo "# Path Comparison"
    echo
    echo "- Generated: $(date -Ins)"
    echo "- Config: $CONFIG"
    echo "- Output root: $OUT_ROOT"
    echo
    echo "| Target | DB listener | Route dev | Via | Src | Ping loss % | Ping avg ms | TNS ms | DBLink single ms | DBLink fetch ms | DBLink repeated ms | DB retr | Failover retr | Output |"
    echo "|---|---|---|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---|"
  } > "$COMPARISON_MD"
}

append_target_summary() {
  local metrics="$1"
  local target_name db_listener route_dev route_via route_src ping_loss ping_avg tnsping nc_status
  local oratcp_small oratcp_medium dblink_single dblink_fetch dblink_repeated dblink_roundtrips dblink_sent dblink_received
  local retr_db retr_oratcp retr_failover pcap_db pcap_failover outdir

  target_name="$(metric_or_blank target_name "$metrics")"
  outdir="$(metric_or_blank outdir "$metrics")"
  db_listener="$(metric_or_blank db_listener "$metrics")"
  route_dev="$(metric_or_blank route_dev "$metrics")"
  route_via="$(metric_or_blank route_via "$metrics")"
  route_src="$(metric_or_blank route_src "$metrics")"
  ping_loss="$(metric_or_blank ping_loss_pct "$metrics")"
  ping_avg="$(metric_or_blank ping_avg_ms "$metrics")"
  tnsping="$(metric_or_blank tnsping_ms "$metrics")"
  nc_status="$(metric_or_blank nc_status "$metrics")"
  oratcp_small="$(metric_or_blank oratcp_small_summary "$metrics")"
  oratcp_medium="$(metric_or_blank oratcp_medium_summary "$metrics")"
  dblink_single="$(metric_or_blank dblink_single_row_elapsed_ms "$metrics")"
  dblink_fetch="$(metric_or_blank dblink_multi_row_elapsed_ms "$metrics")"
  dblink_repeated="$(metric_or_blank dblink_repeated_calls_elapsed_ms "$metrics")"
  dblink_roundtrips="$(metric_or_blank dblink_total_roundtrips_delta "$metrics")"
  dblink_sent="$(metric_or_blank dblink_total_bytes_sent_delta "$metrics")"
  dblink_received="$(metric_or_blank dblink_total_bytes_received_delta "$metrics")"
  retr_db="$(metric_or_blank tcp_retransmissions_db "$metrics")"
  retr_oratcp="$(metric_or_blank tcp_retransmissions_oratcp "$metrics")"
  retr_failover="$(metric_or_blank tcp_retransmissions_failover "$metrics")"
  pcap_db="$(metric_or_blank pcap_db "$metrics")"
  pcap_failover="$(metric_or_blank pcap_failover "$metrics")"

  append_csv_row \
    "$target_name" "$outdir" "$db_listener" "$route_dev" "$route_via" "$route_src" \
    "$ping_loss" "$ping_avg" "$tnsping" "$nc_status" "$oratcp_small" "$oratcp_medium" \
    "$dblink_single" "$dblink_fetch" "$dblink_repeated" "$dblink_roundtrips" \
    "$dblink_sent" "$dblink_received" "$retr_db" "$retr_oratcp" "$retr_failover" \
    "$pcap_db" "$pcap_failover"

  printf '| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |\n' \
    "$target_name" "$db_listener" "$route_dev" "${route_via:-direct}" "$route_src" \
    "$ping_loss" "$ping_avg" "$tnsping" "$dblink_single" "$dblink_fetch" "$dblink_repeated" \
    "$retr_db" "$retr_failover" "$outdir" >> "$COMPARISON_MD"
}

append_failover_summary_if_present() {
  local files
  files="$(find "$OUT_ROOT" -type f -name 'failover_watch_*.csv' -print 2>/dev/null || true)"
  [[ -n "$files" ]] || return 0

  {
    echo
    echo "## Failover Watch Files"
    echo
    while IFS= read -r file; do
      [[ -n "$file" ]] || continue
      local total failures first_failure first_success_after_failure
      total="$(awk -F, 'NR > 1 { n++ } END { print n+0 }' "$file")"
      failures="$(awk -F, 'function clean(s){gsub(/^"|"$/, "", s); gsub(/""/, "\"", s); return s} NR > 1 && clean($4) != "success" { n++ } END { print n+0 }' "$file")"
      first_failure="$(awk -F, 'function clean(s){gsub(/^"|"$/, "", s); gsub(/""/, "\"", s); return s} NR > 1 && clean($4) != "success" { print clean($1); exit }' "$file")"
      first_success_after_failure="$(awk -F, '
        function clean(s){gsub(/^"|"$/, "", s); gsub(/""/, "\"", s); return s}
        NR > 1 && clean($4) != "success" { seen=1 }
        NR > 1 && seen && clean($4) == "success" { print clean($1); exit }
      ' "$file")"
      echo "- $file: probes=$total failures=$failures first_failure=${first_failure:-none} first_success_after_failure=${first_success_after_failure:-none}"
    done <<< "$files"
  } >> "$COMPARISON_MD"
}

write_headers

echo "[INFO] Output root: $OUT_ROOT" | tee "$RUN_LOG"
echo "[INFO] Comparison: $COMPARISON_CSV" | tee -a "$RUN_LOG"
echo "[INFO] Comparison: $COMPARISON_MD" | tee -a "$RUN_LOG"

targets_run=0

if [[ "$REPORT_ONLY" -eq 1 ]]; then
  while IFS= read -r metrics; do
    [[ -n "$metrics" ]] || continue
    append_target_summary "$metrics"
    targets_run=$((targets_run + 1))
  done < <(find "$OUT_ROOT" -type f -name 'metrics.env' -print 2>/dev/null | sort)

  append_failover_summary_if_present

  if [[ "$targets_run" -eq 0 ]]; then
    echo "ERROR: no se encontraron metrics.env bajo $OUT_ROOT." | tee -a "$RUN_LOG"
    exit 1
  fi

  echo
  echo "[OK] Targets consolidados: $targets_run"
  echo "[OK] Comparacion CSV: $COMPARISON_CSV"
  echo "[OK] Comparacion MD : $COMPARISON_MD"
  exit 0
fi

while IFS=, read -r target_name dest_host dest_oratcp_port db_host db_port tns_alias dblink_name db_version iface capture_seconds capture_mode extra; do
  target_name="$(trim "$target_name")"

  [[ -n "$target_name" ]] || continue
  [[ "$target_name" == \#* ]] && continue
  [[ "${target_name,,}" == "target_name" ]] && continue

  dest_host="$(trim "$dest_host")"
  dest_oratcp_port="$(trim "${dest_oratcp_port:-4711}")"
  db_host="$(trim "$db_host")"
  db_port="$(trim "${db_port:-1521}")"
  tns_alias="$(trim "$tns_alias")"
  dblink_name="$(trim "$dblink_name")"
  db_version="$(trim "${db_version:-19c}")"
  iface="$(trim "${iface:-any}")"
  capture_seconds="$(trim "${capture_seconds:-90}")"
  capture_mode="$(trim "${capture_mode:-both}")"

  if [[ -z "$dest_host" || -z "$db_host" || -z "$tns_alias" || -z "$dblink_name" ]]; then
    echo "[WARN] Fila incompleta para target '$target_name'; se omite." | tee -a "$RUN_LOG"
    continue
  fi

  target_safe="$(sanitize_name "$target_name")"
  target_outdir="${OUT_ROOT}/${target_safe}"
  mkdir -p "$target_outdir"

  echo "[INFO] Ejecutando target $target_name -> $target_outdir" | tee -a "$RUN_LOG"

  TARGET_NAME="$target_name" \
  OUTDIR="$target_outdir" \
  CAPTURE_MODE="$capture_mode" \
  "$CLIENT_SCRIPT" \
    "$dest_host" "$dest_oratcp_port" "$db_host" "$db_port" \
    "$tns_alias" "$dblink_name" "$db_version" "$iface" "$capture_seconds" \
    2>&1 | tee -a "$RUN_LOG"

  metrics="${target_outdir}/metrics.env"
  if [[ -f "$metrics" ]]; then
    append_target_summary "$metrics"
  else
    echo "[WARN] No se encontro metrics.env para $target_name" | tee -a "$RUN_LOG"
  fi

  targets_run=$((targets_run + 1))
done < "$CONFIG"

append_failover_summary_if_present

if [[ "$targets_run" -eq 0 ]]; then
  echo "ERROR: no se ejecuto ningun target. Revisa $CONFIG." | tee -a "$RUN_LOG"
  exit 1
fi

echo
echo "[OK] Targets ejecutados: $targets_run"
echo "[OK] Comparacion CSV: $COMPARISON_CSV"
echo "[OK] Comparacion MD : $COMPARISON_MD"
